services:
  express:
    container_name: express
    image: localhost/express:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./debug:/app:Z
    ports:
      - 3000:3000
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./dependencies/prometheus.yaml:/etc/prometheus/prometheus.yaml:Z,ro
    depends_on:
      - express
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3030:3000'
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  grafana-data:
  prometheus-data:
