services:
  nodejs:
    container_name: nodejs
    image: localhost/nodejs:1.0.0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
        #reservations:
        #  cpus: '0.35'
        #  memory: '512M'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/work:Z
    ports:
      - 3000:3000
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml:Z,ro
    depends_on:
      - nodejs
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3030:3000'
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  grafana-data:
  prometheus-data:
