FROM node:18-alpine

# Install dependencies
RUN apk update && apk add --no-cache \
    bash \
    curl

WORKDIR /app
COPY ./debug .
RUN chmod +x entrypoint.sh
RUN npm install

EXPOSE 3000

CMD ["nodemon", "--legacy-watch", "--watch", "/app", "server.js"]