# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json .
COPY server.js .
RUN npm ci --omit=dev

# Stage 2: Runtime
FROM node:18-alpine

WORKDIR /app

# Copy from builder
COPY --from=builder /app .

RUN chmod +x /app/entrypoint.prod.sh

# Drop root privileges
RUN chown -R node:node /app

EXPOSE 3000

CMD ["node", "server.js"]